// apps/dashboard/app/[setId]/page.tsx
import { CasesList } from "@/components/CasesList";
import { getCasesForSet } from "@/queries/getCasesForSet";
import type { FC } from "react";

interface Props {
  params: {
    setId: string;
  };
}

const SetPage: FC<Props> = async ({ params }) => {
  const { setId } = await params;

  const cases = await getCasesForSet(setId);
  const flatCases = cases.flatMap((currentCase) => currentCase.cases);

  return (
    <div className="mt-2 flex flex-col gap-2">
      <CasesList cases={flatCases} slim />
    </div>
  );
};

export default SetPage;

// apps/client/src/routes/[setId]/+page.svelte
<script lang="ts">
	import { page } from '$app/state';
	import CasesList from '$lib/components/CasesList.svelte';
	import PreviewList from '$lib/components/PreviewList.svelte';
	import { getSetView } from '$lib/data/catalog.remote';

	const view = $derived(await getSetView(page.params.setId));
</script>

<PreviewList items={view.items} />
<div class="mt-2 flex flex-col gap-2">
	<CasesList cases={view.cases} slim />
</div>
