// cubing/src/components/AlgorithmsList/AlgorithmsList.tsx
import type { FC } from "react";
import { AlgorithmView } from "@/components/AlgorithmView";
import { Chip } from "@nextui-org/chip";
import { cn } from "@nextui-org/react";
import type { ViewType } from "src/content.config";
import type { Case } from "@/components/CaseView";

const otherAlgorithmsLimit = 2;

interface Props {
  className?: string;
  setup: string;
  algorithms: Case["algorithms"];
  mainAlgorithmId?: string;
  slim: boolean;
  viewType: ViewType;
}

export const AlgorithmsList: FC<Props> = ({
  className,
  setup,
  algorithms,
  mainAlgorithmId,
  slim,
  viewType,
}) => {
  const mainAlgorithm = algorithms.find(
    (algorithm) => algorithm.id === mainAlgorithmId,
  );
  const otherAlgorithms = algorithms.filter(
    (algorithm) => algorithm.id !== mainAlgorithm?.id,
  );
  const limitedOtherAlgorithms = otherAlgorithms.slice(
    0,
    slim ? otherAlgorithmsLimit : otherAlgorithms.length,
  );
  const hasMore = otherAlgorithms.length > limitedOtherAlgorithms.length;

  return (
    <div className={cn(className, "flex flex-col gap-1")}>
      {mainAlgorithm ? (
        <AlgorithmView
          key={mainAlgorithm.id}
          setup={setup}
          algorithm={mainAlgorithm}
          slim={slim}
          viewType={viewType}
          isMain
        />
      ) : (
        <div className="rounded-md border-2 border-cube-red p-1 text-center text-2xl">
          (No main algorithm)
        </div>
      )}
      {limitedOtherAlgorithms.map((algorithm) => (
        <AlgorithmView
          key={algorithm.id}
          setup={setup}
          algorithm={algorithm}
          slim={slim}
          viewType={viewType}
        />
      ))}
      {hasMore && (
        <Chip className="self-center" color="primary">
          +{otherAlgorithms.length - limitedOtherAlgorithms.length}
        </Chip>
      )}
    </div>
  );
};

// apps/client/src/lib/components/AlgorithmsList.svelte
<script lang="ts">
	import type { Algorithm, ViewType } from "$lib/data/types";
	import AlgorithmView from "./AlgorithmView.svelte";

	const otherAlgorithmsLimit = 2;

	interface Props {
		class?: string;
		setup: string;
		algorithms: Algorithm[];
		defaultAlgorithmId: string | null;
		slim: boolean;
		viewType: ViewType;
	}

	let {
		class: className = "",
		setup,
		algorithms,
		defaultAlgorithmId,
		slim,
		viewType,
	}: Props = $props();

	const mainAlgorithm = $derived(
		algorithms.find((a) => a.id === defaultAlgorithmId) ?? algorithms[0],
	);
	const otherAlgorithms = $derived(algorithms.filter((a) => a.id !== mainAlgorithm?.id));
	const limitedOtherAlgorithms = $derived(
		otherAlgorithms.slice(0, slim ? otherAlgorithmsLimit : otherAlgorithms.length),
	);
	const hasMore = $derived(otherAlgorithms.length > limitedOtherAlgorithms.length);
</script>

<div class={[className, 'flex flex-col gap-2']}>
	<AlgorithmView {setup} algorithm={mainAlgorithm} {slim} {viewType} isMain />
	{#each limitedOtherAlgorithms as algorithm (algorithm.id)}
		<AlgorithmView {setup} {algorithm} {slim} {viewType} />
	{/each}
	{#if hasMore}
		<span
			class="self-center rounded-full border border-base-300 px-2.5 py-0.5 text-xs font-semibold text-base-content/60"
		>
			+{otherAlgorithms.length - limitedOtherAlgorithms.length}
			more
		</span>
	{/if}
</div>
