// apps/client/src/layouts/Breadcrumbs.tsx
import { type FC, Fragment } from "react";
import {
	Breadcrumb,
	BreadcrumbItem,
	BreadcrumbLink,
	BreadcrumbList,
	BreadcrumbPage,
	BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";

export interface BreadcrumbEntry {
	name: string;
	href: string;
}

interface BreadcrumbsProps {
	breadcrumbs: BreadcrumbEntry[];
}

export const Breadcrumbs: FC<BreadcrumbsProps> = ({ breadcrumbs }) => {
	const links = breadcrumbs.slice(0, -1);
	const active = breadcrumbs.at(-1);

	return (
		<Breadcrumb>
			<BreadcrumbList>
				{links.map((link, index) => (
					<Fragment key={link.href}>
						{!!index && <BreadcrumbSeparator className="hidden md:block" />}
						<BreadcrumbItem className="hidden md:block">
							<BreadcrumbLink href={link.href}>{link.name}</BreadcrumbLink>
						</BreadcrumbItem>
					</Fragment>
				))}
				{active && (
					<Fragment key="active">
						{!!links.length && (
							<BreadcrumbSeparator className="hidden md:block" />
						)}
						<BreadcrumbItem>
							<BreadcrumbPage>{active.name}</BreadcrumbPage>
						</BreadcrumbItem>
					</Fragment>
				)}
			</BreadcrumbList>
		</Breadcrumb>
	);
};

// apps/client/src/lib/components/Breadcrumbs.svelte
<script lang="ts">
	import type { Breadcrumb } from '$lib/data/types';

	interface Props {
		breadcrumbs: Breadcrumb[];
	}

	let { breadcrumbs }: Props = $props();

	const links = $derived(breadcrumbs.slice(0, -1));
	const active = $derived(breadcrumbs.at(-1));
</script>

<div class="breadcrumbs text-sm">
	<ul>
		{#each links as link (link.href)}
			<li><a href={link.href}>{link.name}</a></li>
		{/each}
		{#if active}
			<li>{active.name}</li>
		{/if}
	</ul>
</div>
