// apps/dashboard/components/CasesList/CasesList.tsx
import { CaseView } from "@/components/CaseView";
import type { GetCasesEntity } from "@/queries/getCases";
import type { FC } from "react";

interface Props {
  cases: GetCasesEntity[];
  slim: boolean;
}

export const CasesList: FC<Props> = ({ cases, slim }) => (
  <div className="flex flex-col items-center gap-4">
    {cases.map((currentCase) => (
      <CaseView key={currentCase.id} case={currentCase} slim={slim} />
    ))}
    {!cases.length && <div className="text-2xl uppercase">No cases</div>}
  </div>
);

// apps/client/src/lib/components/CasesList.svelte
<script lang="ts">
	import type { CaseWithContext } from '$lib/data/types';
	import CaseView from './CaseView.svelte';

	interface Props {
		cases: CaseWithContext[];
		slim: boolean;
	}

	let { cases, slim }: Props = $props();
</script>

<div class="flex flex-col items-center gap-4">
	{#each cases as c (c.id)}
		<a class="w-full" href={`/${c.subset.setId}/${c.subset.id}/${c.id}`}>
			<CaseView case={c} {slim} />
		</a>
	{/each}
	{#if cases.length === 0}
		<div class="text-2xl uppercase">No cases</div>
	{/if}
</div>
