// apps/dashboard/app/[setId]/[subsetId]/page.tsx
import { CasesList } from "@/components/CasesList";
import { getCasesForSubset } from "@/queries/getCasesForSubset";
import { getSubsets } from "@/queries/getSubsets";
import type { FC } from "react";

export const generateStaticParams = async ({ params: { setId } }: Props) => {
  const subsets = await getSubsets(setId);

  return subsets.map(({ id }) => ({
    subsetId: id,
  }));
};

interface Props {
  params: {
    setId: string;
    subsetId: string;
  };
}

const SubsetPage: FC<Props> = async ({ params: { subsetId } }) => {
  const cases = await getCasesForSubset(subsetId);

  return (
    <div className="mt-2 flex flex-col gap-2">
      <CasesList cases={cases} slim />
    </div>
  );
};

export default SubsetPage;

// apps/client/src/routes/[setId]/[subsetId]/+page.svelte
<script lang="ts">
	import { page } from '$app/state';
	import CasesList from '$lib/components/CasesList.svelte';
	import PreviewList from '$lib/components/PreviewList.svelte';
	import { getSubsetView } from '$lib/data/catalog.remote';

	const view = $derived(
		await getSubsetView({ setId: page.params.setId, subsetId: page.params.subsetId })
	);
</script>

<PreviewList items={view.items} />
<div class="mt-2 flex flex-col gap-2">
	<CasesList cases={view.cases} slim />
</div>
