// src/components/F2L/F2L.tsx
import type { FC } from "react";
import { Face } from "@/components/Face";
import { algorithmToFaces } from "@/cube/compound/algorithmToFaces";
import { Colors } from "@/cube/types/Colors";

interface Props {
  algorithm: string;
}

export const F2L: FC<Props> = ({ algorithm }) => {
  const faces = algorithmToFaces({
    algorithm,
    orientation: { U: Colors.Y, F: Colors.R },
  });

  return (
    <div className="relative flex aspect-square items-end">
      <Face
        className="absolute bottom-[65%] !h-[66%] !w-[66%] transform [--tw-scale-y:0.5] [--tw-skew-x:-45deg] [--tw-translate-x:25%] [--tw-translate-y:25%]"
        face={faces.U}
        maskedColors={[Colors.Y, Colors.B, Colors.O]}
      />
      <Face
        className="!h-[66%] !w-[66%]"
        face={faces.F}
        maskedColors={[Colors.Y, Colors.B, Colors.O]}
      />
      <Face
        className="absolute left-[65%] top-[34%] !h-[66%] !w-[66%] transform [--tw-scale-x:0.5] [--tw-skew-y:-45deg] [--tw-translate-x:-25%] [--tw-translate-y:-25%]"
        face={faces.R}
        maskedColors={[Colors.Y, Colors.B, Colors.O]}
      />
    </div>
  );
};

// apps/client/src/lib/components/cube/F2L.svelte
<script lang="ts">
	import { algorithmToFaces, Colors } from 'cube';
	import Face from './Face.svelte';

	interface Props {
		algorithm: string;
	}

	let { algorithm }: Props = $props();

	const faces = $derived(
		algorithmToFaces({ algorithm, orientation: { U: Colors.Y, F: Colors.R } })
	);
</script>

<div class="grid aspect-square origin-bottom-left scale-125 grid-cols-2 grid-rows-2">
	<Face
		class="row-start-1 h-1/2 origin-bottom-left translate-y-full -skew-x-45"
		face={faces.U}
		maskedColors={[Colors.Y, Colors.B, Colors.O]}
	/>
	<Face class="row-start-2" face={faces.F} maskedColors={[Colors.Y, Colors.B, Colors.O]} />
	<Face
		class="row-start-2 w-1/2 origin-bottom-left -skew-y-45"
		face={faces.R}
		maskedColors={[Colors.Y, Colors.B, Colors.O]}
	/>
</div>
