// apps/dashboard/components/LastLayer/LastLayer.tsx
import type { FC } from "react";
import {
  Colors,
  algorithmToFaces,
  type ColorOrientation,
  getAdjacentPieces,
  Faces,
} from "@/cube";
import { Face } from "@/components/Face";

interface Props {
  algorithm: string;
  maskedColors?: Colors[];
  orientation?: ColorOrientation;
}

export const LastLayer: FC<Props> = ({
  algorithm,
  maskedColors = [],
  orientation = { U: Colors.Y, F: Colors.G },
}) => {
  const faces = algorithmToFaces({
    algorithm,
    orientation,
  });
  const adjacentColors = getAdjacentPieces(faces, Faces.U);

  return (
    <Face
      face={faces.U}
      maskedColors={maskedColors}
      adjacentPieces={adjacentColors}
    />
  );
};

// apps/client/src/lib/components/cube/LastLayer.svelte
<script lang="ts">
	import { algorithmToFaces, type ColorOrientation, Colors, Faces, getAdjacentPieces } from 'cube';
	import Face from './Face.svelte';

	interface Props {
		algorithm: string;
		maskedColors?: Colors[];
		orientation?: ColorOrientation;
	}

	let {
		algorithm,
		maskedColors = [],
		orientation = { U: Colors.Y, F: Colors.G }
	}: Props = $props();

	const faces = $derived(algorithmToFaces({ algorithm, orientation }));
	const adjacentColors = $derived(getAdjacentPieces(faces, Faces.U));
</script>

<Face face={faces.U} {maskedColors} adjacentPieces={adjacentColors} />
