// apps/client/src/lib/layout/AppSidebar.svelte
<script lang="ts">
	import { Box, Search } from '@lucide/svelte';
	import { page } from '$app/state';
	import type { SidebarCube } from '$lib/data/types';

	interface Props {
		sidebar: SidebarCube[];
	}

	let { sidebar }: Props = $props();

	let query = $state('');

	const filtered = $derived.by(() => {
		const q = query.toLowerCase();
		return sidebar
			.map((cube) => ({
				...cube,
				sets: cube.sets
					.map((set) => ({
						...set,
						subsets: set.subsets
							.map((subset) =>
								subset.name.toLowerCase().includes(q)
									? subset
									: {
											...subset,
											cases: subset.cases.filter((c) => c.name.toLowerCase().includes(q))
										}
							)
							.filter((subset) => subset.cases.length > 0)
					}))
					.filter((set) => set.subsets.length > 0)
			}))
			.filter((cube) => cube.sets.length > 0);
	});

	const isActive = (href: string) => page.url.pathname === href;

	const activeBar = 'shadow-[inset_3px_0_0_0_var(--type-accent)]';
</script>

<aside class="flex min-h-full w-72 flex-col gap-3 border-r border-base-300 bg-base-100 p-4">
	<a href="/" class="flex items-center gap-2.5 px-2 py-1">
		<span
			class="cube-gradient flex size-8 items-center justify-center rounded-lg text-white shadow-sm"
		>
			<Box class="size-4" />
		</span>
		<span class="text-base font-bold tracking-tight">Algorithms</span>
	</a>

	<label class="input input-sm w-full rounded-field">
		<Search class="size-4 opacity-50" />
		<input
			type="search"
			aria-label="Search for algs"
			placeholder="Search for algs"
			bind:value={query}
		/>
	</label>

	<ul class="menu w-full grow flex-nowrap gap-0.5 overflow-y-auto px-0">
		{#each filtered as cube (cube.id)}
			<li class="menu-title px-0">
				<a href={`/${cube.id}`} class={['font-bold', isActive(`/${cube.id}`) && 'text-base-content']}>
					{cube.name}
				</a>
			</li>
			{#each cube.sets as set (set.id)}
				<li data-type={set.viewType}>
					<a
						href={`/${cube.id}/${set.id}`}
						class={[
							'gap-2.5 font-semibold transition-colors',
							isActive(`/${cube.id}/${set.id}`) && `bg-(--type-soft) ${activeBar}`
						]}
					>
						<span class="size-2.5 rounded-[3px] bg-(--type-accent)"></span>
						{set.name}
					</a>
					<ul class="border-base-300">
						{#each set.subsets as subset (subset.id)}
							<li>
								<a
									href={`/${cube.id}/${set.id}/${subset.id}`}
									class={[
										'transition-colors',
										isActive(`/${cube.id}/${set.id}/${subset.id}`) &&
											`bg-(--type-soft) font-medium ${activeBar}`
									]}
								>
									{subset.name}
								</a>
								<ul>
									{#each subset.cases as c (c.id)}
										<li>
											<a
												href={`/${cube.id}/${set.id}/${subset.id}/${c.id}`}
												class={[
													'transition-colors',
													isActive(`/${cube.id}/${set.id}/${subset.id}/${c.id}`) &&
														`bg-(--type-soft) font-medium ${activeBar}`
												]}
											>
												{c.name}
											</a>
										</li>
									{/each}
								</ul>
							</li>
						{/each}
					</ul>
				</li>
			{/each}
		{/each}
	</ul>
</aside>

// src/layouts/AppSidebar.tsx
import { GalleryVerticalEnd } from "lucide-react";

import {
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarMenuSub,
  SidebarMenuSubButton,
  SidebarMenuSubItem,
  SidebarRail,
} from "@/components/ui/sidebar";
import { SearchForm } from "@/layouts/SearchForm";
import { useState, type ComponentProps, type FC } from "react";
import type { InferEntrySchema } from "astro:content";

type Case = InferEntrySchema<"cases">;
type Subset = InferEntrySchema<"subsets"> & { cases: Case[] };
export type Set = InferEntrySchema<"sets"> & { subsets: Subset[] };

interface AppSidebarProps extends ComponentProps<typeof Sidebar> {
  sets: Set[];
  pathname: string;
}

export const AppSidebar: FC<AppSidebarProps> = ({
  sets,
  pathname,
  ...props
}) => {
  const [query, setQuery] = useState("");
  const filteredSets = sets
    .map((set) => {
      const subsets = set.subsets.map((subset) => {
        if (subset.name.toLowerCase().includes(query.toLowerCase()))
          return subset;

        const cases = subset.cases.filter((c) =>
          c.name.toLowerCase().includes(query.toLowerCase()),
        );
        return { ...subset, cases };
      });
      return { ...set, subsets };
    })
    .map((set) => {
      const subsets = set.subsets.filter((subset) => subset.cases.length > 0);

      return { ...set, subsets };
    })
    .filter((set) => set.subsets.length > 0);

  return (
    <Sidebar {...props}>
      <SidebarHeader>
        <SidebarMenu>
          <SidebarMenuItem>
            <SidebarMenuButton size="lg" asChild>
              <a href="/">
                <div className="flex aspect-square size-8 items-center justify-center rounded-lg bg-sidebar-primary text-sidebar-primary-foreground">
                  <GalleryVerticalEnd className="size-4" />
                </div>
                <div className="flex flex-col gap-0.5 leading-none">
                  <span className="font-semibold">Algorithms</span>
                </div>
              </a>
            </SidebarMenuButton>
          </SidebarMenuItem>
        </SidebarMenu>
        <SearchForm query={query} setQuery={setQuery} />
      </SidebarHeader>
      <SidebarContent>
        {filteredSets.map((set) => (
          <SidebarGroup key={set.id}>
            <SidebarGroupLabel>{set.name}</SidebarGroupLabel>
            <SidebarGroupContent>
              <SidebarMenu>
                {set.subsets.map((subset) => {
                  const subsetHref = `/${set.id}/${subset.id}`;

                  return (
                    <SidebarMenuItem key={subset.id}>
                      <SidebarMenuButton
                        asChild
                        isActive={pathname === subsetHref}
                      >
                        <a href={`/${set.id}/${subset.id}`}>{subset.name}</a>
                      </SidebarMenuButton>
                      <SidebarMenuSub>
                        {subset.cases.map((currentCase) => {
                          const caseHref = `${subsetHref}/${currentCase.id}`;

                          return (
                            <SidebarMenuSubItem key={currentCase.id}>
                              <SidebarMenuSubButton
                                asChild
                                isActive={pathname === caseHref}
                              >
                                <a href={caseHref}>{currentCase.name}</a>
                              </SidebarMenuSubButton>
                            </SidebarMenuSubItem>
                          );
                        })}
                      </SidebarMenuSub>
                    </SidebarMenuItem>
                  );
                })}
              </SidebarMenu>
            </SidebarGroupContent>
          </SidebarGroup>
        ))}
      </SidebarContent>
      <SidebarRail />
    </Sidebar>
  );
};
